### ISSUE TITLE
How to use in the cloud?

### ISSUE THREAD

**Issue by wazlecracker** [saeoshi/TA_Akamai_DataStream_Addon#1]
How does one go about implementing this in the cloud? I have datastreams coming in via HEC, does this addon automatically parse them? I'm not seeing any difference in the fields compared to before installation.

**Comment by saeoshi** [comment]
I do have this addon set to parse automatically.
Which one do you use for sourcetype?

If you can get me a sample log, I'll check it out!

**Comment by wazlecracker** [comment]
Never entered a sourcetype and it seemed to parse the JSON pretty well. Which would be best to pick?

**Comment by saeoshi** [comment]
Can you try to specify akamai-datastream-raw for sourcetype?

**Comment by wazlecracker** [comment]
That works much better, thank you!
